-- Per-business SMS sender identity + owner-editable message text, replacing the hardcoded "Lucy"
-- persona and the fixed in-code wording every automation used to send unconditionally.
--
-- sender_name: who every automated (and AI-drafted) SMS signs as — defaults to 'Lucy' so every
-- existing business keeps today's exact wording with no action needed.
ALTER TABLE twilio_sms_config
    ADD COLUMN sender_name VARCHAR(50) NOT NULL DEFAULT 'Lucy';

-- sms_template_override: an owner's custom body for one template_key, business-scoped. Absence of
-- a row (the common case) means "use the in-code default" — see SmsMessageTemplateCatalog. Only
-- the raw text is editable here; SmsMessageClass (transactional vs. marketing, which gates consent
-- requirements) stays fixed in code per template_key, never settable by an owner — same safety
-- property SmsTemplateRegistry's own doc comment already established for the pre-existing templates.
CREATE TABLE sms_template_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES business(id),
    template_key VARCHAR(100) NOT NULL,
    body TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by VARCHAR(255),
    UNIQUE (business_id, template_key)
);
