-- Owner-configurable discount amount/minimum-spend per business per promo code, backing the
-- signed REBOOK10/WINBACK5 short links (same_day_rebooking_discount / lapsed_customer_winback +
-- repeat_customer_winback, which reuses the WINBACK5 row). No row for Business A (short_code
-- 'akluxnails') — it keeps running on the pre-existing env-based RebookingProperties config
-- (real Square Catalog/CustomerGroup ids were never captured in this app, only in env vars), so
-- this table only ever backs a business onboarded after this migration.
CREATE TABLE business_promo_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES business(id),
    promo_code VARCHAR(20) NOT NULL,
    discount_cents INTEGER NOT NULL,
    min_spend_cents INTEGER,
    square_customer_group_id VARCHAR(100),
    square_discount_catalog_id VARCHAR(100),
    square_pricing_rule_catalog_id VARCHAR(100),
    square_product_set_catalog_id VARCHAR(100),
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by VARCHAR(255),
    UNIQUE (business_id, promo_code)
);
