-- Per-business runtime config for outbound marketing email via Mailchimp, same shape as
-- twilio_sms_config (V46/V95) — owner-editable at /api/owner/settings/mailchimp. Seeded with no
-- rows; a business simply has no Mailchimp config until the owner sets one up, same "isConfigured()
-- gates everything, nothing else breaks if unset" convention Twilio already uses.
CREATE TABLE mailchimp_config (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id    BIGINT NOT NULL UNIQUE REFERENCES business(id),
    api_key        TEXT,          -- Mailchimp API key, e.g. "abc123...-us21" — the "-us21" suffix
                                   -- is the datacenter/server prefix the API base URL is built from.
    audience_id    TEXT,          -- Mailchimp Audience/List ID the win-back automations add contacts to.
    from_name      TEXT,          -- Campaign "from name" Mailchimp requires on every send.
    reply_to_email TEXT,          -- Campaign "reply-to" address Mailchimp requires on every send.
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by     TEXT
);
