-- Idempotency + outcome log for the win-back email fallback (WinbackEmailFallbackScheduler):
-- SMS goes out first (LapsedCustomerWinbackScheduler / RepeatCustomerWinbackScheduler); this table
-- tracks the evening follow-up email sent only to customers who neither clicked their SMS link nor
-- replied by then. One row per sms_message.id, ever — the unique constraint is the idempotency
-- key, same "claim before send" reasoning as lapsed_customer_winback_send.
CREATE TABLE winback_email_send (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id          BIGINT NOT NULL REFERENCES business(id),
    automation_key       TEXT NOT NULL, -- 'lapsed_customer_winback' | 'repeat_customer_winback'
    sms_message_id       BIGINT NOT NULL UNIQUE REFERENCES sms_message(id),
    square_customer_id   TEXT NOT NULL,
    email_address        TEXT,
    state                TEXT NOT NULL, -- SENT | SKIPPED_CLICKED | SKIPPED_REPLIED | SKIPPED_NO_EMAIL
                                         -- | SKIPPED_DISABLED | SKIPPED_NOT_CONFIGURED | SKIPPED_NO_TEMPLATE
    mailchimp_campaign_id TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX winback_email_send_business_customer_idx ON winback_email_send(business_id, square_customer_id);
