-- Local mirror of Square's Bookings, backfilled and kept fresh via webhook + periodic
-- reconciliation (see SquareBookingMirrorIngestService) — lets marketing dashboard reads query
-- our own DB instead of a live Square API call per contact, which was the root cause of
-- /owner/marketing's slowness for high-contact-count businesses. See the Phase 1 plan for the
-- full rationale; this table is deliberately raw (unmatched, unmodified Square data), not derived
-- like provider_visit.
CREATE TABLE square_booking (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id               BIGINT NOT NULL REFERENCES business(id),
    square_booking_id         TEXT NOT NULL,
    square_customer_id        TEXT,              -- raw Square id, pre-canonicalization; resolved at read time
    status                    TEXT NOT NULL,
    start_at                  TIMESTAMPTZ,
    created_at                TIMESTAMPTZ,
    updated_at                TIMESTAMPTZ,
    location_id               TEXT,
    seller_note               TEXT,
    customer_note             TEXT,
    appointment_segments_json JSONB,
    synced_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (business_id, square_booking_id)
);

CREATE INDEX square_booking_business_customer_idx ON square_booking(business_id, square_customer_id);
CREATE INDEX square_booking_business_updated_idx ON square_booking(business_id, updated_at);
