-- Local mirrors of Square's Orders and Payments, same rationale/lifecycle as V133's square_booking
-- (see SquareBookingMirrorIngestService's own doc). Together with square_booking these let the
-- marketing dashboard answer "what did this appointment collect" locally instead of calling
-- SquareMonthAggregator.aggregate() once per contact (the same heavy payroll computation /reports
-- uses) — see MarketingBookingPaymentMatcher, which reads these tables directly and is deliberately
-- NOT shared code with the aggregator.
CREATE TABLE square_order (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES business(id),
    square_order_id    TEXT NOT NULL,
    square_customer_id TEXT,
    state              TEXT,
    closed_at          TIMESTAMPTZ,
    created_at         TIMESTAMPTZ,
    total_tip_money    NUMERIC(10,2),
    total_discount_money NUMERIC(10,2),
    tenders_json       JSONB,
    line_items_json    JSONB,
    synced_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (business_id, square_order_id)
);

CREATE INDEX square_order_business_customer_idx ON square_order(business_id, square_customer_id);
CREATE INDEX square_order_business_closed_idx ON square_order(business_id, closed_at);

CREATE TABLE square_payment (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES business(id),
    square_payment_id  TEXT NOT NULL,
    square_order_id    TEXT,
    square_customer_id TEXT,
    status             TEXT,
    created_at         TIMESTAMPTZ,
    total_money        NUMERIC(10,2),
    tip_money          NUMERIC(10,2),
    synced_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (business_id, square_payment_id)
);

CREATE INDEX square_payment_business_customer_idx ON square_payment(business_id, square_customer_id);
CREATE INDEX square_payment_business_order_idx ON square_payment(business_id, square_order_id);
