-- Local mirror of Square's Customers — backfilled and kept fresh via webhook + a periodic full
-- re-sync (see SquareCustomerMirrorIngestService), so phone->customerId resolution can query our
-- own DB instead of a live Square customers/search call per contact. Found 2026-08-29: this exact
-- live-call-per-contact pattern is what made the Ads Report take ~22s cold for ~93 contacts, and
-- what (until a separate fix that same day) made canonicalCustomerIds/customerNames re-fetch every
-- customer of a payroll month live every time SquareClientProvider rebuilt its client. See the
-- Phase 3 plan for the full rationale.
CREATE TABLE square_customer (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES business(id),
    square_customer_id TEXT NOT NULL,
    phone_number       TEXT,              -- normalized E.164, matching SquareClient#normalizePhone
    given_name         TEXT,
    family_name        TEXT,
    email_address      TEXT,
    square_created_at  TIMESTAMPTZ,
    synced_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (business_id, square_customer_id)
);

CREATE INDEX square_customer_business_phone_idx ON square_customer(business_id, phone_number);
