-- Microsoft Clarity tracking-code project id, one row per public-facing site — keyed by the
-- site's own real hostname (not a hand-rolled site-key enum) so it slots directly into the same
-- domain-resolution mechanism InternalBusinessController#byDomain and salonLandings'
-- business_context.py already use, rather than inventing a second lookup concept for the same
-- problem. Not a secret (a Clarity project id is visible in any page's own source once live), so
-- no encryption-at-rest needed — plain text, like SeoConnection's ga4MeasurementId.
CREATE TABLE tracking_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id         BIGINT NOT NULL REFERENCES business(id),
    hostname            TEXT NOT NULL,
    clarity_project_id  TEXT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by          TEXT,
    UNIQUE (hostname)
);

-- Seeded with every known public site today, clarity_project_id left NULL (owner fills it in via
-- /owner/settings/tracking) — see TrackingConfigService's SITE_LABELS for the matching human
-- labels. A future new site is just another row, added alongside deploying that site's own code.
-- Guarded by an EXISTS check against `business`, same convention V142 uses for its own seed —
-- business rows aren't Flyway-seeded (they're created by the app/tests), so a fresh test database
-- has none yet and this becomes a no-op there instead of a foreign-key violation.
INSERT INTO tracking_config (business_id, hostname)
SELECT v.business_id, v.hostname
FROM (VALUES
    (1, 'akluxnails.com'),
    (1, 'mani.akluxnails.com'),
    (2, 'book.pmu-annakara.com')
) AS v(business_id, hostname)
WHERE EXISTS (SELECT 1 FROM business WHERE business.id = v.business_id);
