-- salon_config.id was never a real sequence — V1 gave it a static `DEFAULT 1` because the table
-- was designed as a strict one-row singleton (see its own CHECK(id = 1), dropped by V86 once
-- business scoping made a second row possible). Nothing since then gave this column a way to
-- generate an id for a second business's row. Converts it to a proper Postgres identity column,
-- seeded past the existing row so the next insert doesn't collide with it.
ALTER TABLE salon_config ALTER COLUMN id DROP DEFAULT;
ALTER TABLE salon_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('salon_config', 'id'), (SELECT COALESCE(MAX(id), 0) FROM salon_config));
