-- Phase 2.6: twilio_sms_config was a hardcoded singleton (id BOOLEAN PRIMARY KEY DEFAULT TRUE) from
-- before multi-tenancy existed — a boolean PK fundamentally cannot support more than one row, which
-- is exactly why SmsBusinessScopeFilter had to block every business but A from this data entirely
-- (see that class's own doc comment) rather than give each business its own Twilio number. This
-- gives it a real per-business identity, same shape as square_connection: a fresh bigint identity
-- id as the primary key, business_id as a UNIQUE FK. The existing row (if any) is backfilled to
-- Business A, since that's the only business that has ever used this table.

ALTER TABLE twilio_sms_config ADD COLUMN business_id BIGINT;
UPDATE twilio_sms_config SET business_id = (SELECT id FROM business WHERE short_code = 'akluxnails');

ALTER TABLE twilio_sms_config DROP CONSTRAINT twilio_sms_config_pkey;
ALTER TABLE twilio_sms_config DROP CONSTRAINT twilio_sms_config_id_check;
ALTER TABLE twilio_sms_config DROP COLUMN id;
ALTER TABLE twilio_sms_config ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE twilio_sms_config ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE twilio_sms_config ADD CONSTRAINT twilio_sms_config_business_id_key UNIQUE (business_id);
ALTER TABLE twilio_sms_config ADD CONSTRAINT twilio_sms_config_business_id_fkey
    FOREIGN KEY (business_id) REFERENCES business(id);
