-- Same surgery as V95, for the same reason — see that migration's own comment.
ALTER TABLE telegram_notification_config ADD COLUMN business_id BIGINT;
UPDATE telegram_notification_config SET business_id = (SELECT id FROM business WHERE short_code = 'akluxnails');

ALTER TABLE telegram_notification_config DROP CONSTRAINT telegram_notification_config_pkey;
ALTER TABLE telegram_notification_config DROP CONSTRAINT telegram_notification_config_id_check;
ALTER TABLE telegram_notification_config DROP COLUMN id;
ALTER TABLE telegram_notification_config ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

ALTER TABLE telegram_notification_config ALTER COLUMN business_id SET NOT NULL;
ALTER TABLE telegram_notification_config ADD CONSTRAINT telegram_notification_config_business_id_key UNIQUE (business_id);
ALTER TABLE telegram_notification_config ADD CONSTRAINT telegram_notification_config_business_id_fkey
    FOREIGN KEY (business_id) REFERENCES business(id);
