package com.salonreview.marketing;

import java.util.Set;
import java.util.stream.Collectors;

/**
 * Shared classification of a visit/contact into one of five owner-facing traffic-source buckets —
 * {@code meta_ads}, {@code google_ads}, {@code instagram_organic}, {@code google_organic},
 * {@code direct} — used identically by {@link MarketingDashboardRepository},
 * {@link FunnelAnalyticsRepository}, and {@link MarketingContactsRepository} so every marketing
 * tab agrees on what counts as what. Replaces the old AdsTrafficSql's "any fbclid/gclid = ads"
 * rule.
 *
 * <p><b>Why fbclid alone isn't proof of a paid click:</b> Meta's Instagram/Facebook apps attach
 * fbclid to every outbound link tap made from inside the app — paid ad or not — confirmed against
 * this app's own data: a handful of visits carry fbclid, utm_source=ig, utm_medium=social,
 * utm_content=link_in_bio, and a referrer of https://l.instagram.com/ — the exact fingerprint of
 * someone tapping the salon's Instagram bio link, not an ad. A real Meta ad, by contrast, always
 * carries a placement-specific utm_medium auto-generated by Ads Manager's dynamic UTM parameters
 * (e.g. Instagram_Feed, Instagram_Stories, Facebook_Mobile_Reels) — an organic bio-link/post-share
 * tap never gets one of these; at most utm_medium=social, or nothing at all. So "paid" here means
 * a click id *and* a real placement medium, not the click id by itself. Google's gclid has no such
 * ambiguity — Google never attaches it to an organic result — so gclid alone is always enough.
 */
final class TrafficSourceSql {

    private TrafficSourceSql() {}

    static final String META_ADS = "meta_ads";
    static final String GOOGLE_ADS = "google_ads";
    static final String INSTAGRAM_ORGANIC = "instagram_organic";
    static final String GOOGLE_ORGANIC = "google_organic";
    static final String DIRECT = "direct";

    /** Every recognized bucket — the full "All traffic" set. */
    static final Set<String> ALL = Set.of(META_ADS, GOOGLE_ADS, INSTAGRAM_ORGANIC, GOOGLE_ORGANIC, DIRECT);

    /** Default ("Ads only") selection — mani runs ads, so this is the more useful default view there. */
    static final Set<String> ADS_ONLY = Set.of(META_ADS, GOOGLE_ADS);

    /** Classifies a marketing.visits row. %1$s is the table alias (e.g. "vi"). A visit that
     * matches none of these (e.g. a referrer from some other site, or fbclid with no medium at
     * all) classifies NULL — visible under "All traffic" but not selectable as its own bucket,
     * the same tradeoff already accepted for edge cases elsewhere in this schema. */
    private static final String VISIT_CASE = """
            CASE
                WHEN %1$s.gclid IS NOT NULL THEN 'google_ads'
                WHEN %1$s.fbclid IS NOT NULL AND COALESCE(%1$s.utm_medium, '') <> 'social' THEN 'meta_ads'
                WHEN %1$s.utm_source ILIKE 'ig' AND COALESCE(%1$s.utm_medium, '') IN ('', 'social') THEN 'instagram_organic'
                WHEN %1$s.referrer ILIKE '%%instagram.com%%' THEN 'instagram_organic'
                WHEN %1$s.utm_source IS NULL AND %1$s.referrer ILIKE '%%google.%%' THEN 'google_organic'
                WHEN %1$s.utm_source IS NULL AND %1$s.fbclid IS NULL AND %1$s.gclid IS NULL
                     AND (%1$s.referrer IS NULL OR %1$s.referrer = '') THEN 'direct'
                ELSE NULL
            END""";

    /** Classifies a marketing.contacts row. marketing.contacts has no fbclid/gclid columns — only
     * the already-classified label (computed by salonLandings' classify_traffic_source(), which
     * inherits the same "fbclid alone = ads" blind spot described above) plus its own utm/referrer.
     * So this trusts the label for "is this a recognized ad platform at all", but *additionally*
     * requires a real placement medium before accepting "Meta Ads" — the same fix as VISIT_CASE,
     * applied without needing a click-id column. %1$s is the table alias (e.g. "c"). */
    private static final String CONTACT_CASE = """
            CASE
                WHEN %1$s.marketing_traffic_source LIKE 'Google Ads%%' OR %1$s.original_traffic_source LIKE 'Google Ads%%'
                     THEN 'google_ads'
                WHEN (%1$s.marketing_traffic_source LIKE 'Meta Ads%%' OR %1$s.original_traffic_source LIKE 'Meta Ads%%')
                     AND %1$s.utm_medium IS NOT NULL AND %1$s.utm_medium <> 'social' THEN 'meta_ads'
                WHEN %1$s.utm_source ILIKE 'ig' AND COALESCE(%1$s.utm_medium, '') IN ('', 'social') THEN 'instagram_organic'
                WHEN %1$s.referrer ILIKE '%%instagram.com%%' THEN 'instagram_organic'
                WHEN %1$s.utm_source IS NULL AND %1$s.referrer ILIKE '%%google.%%' THEN 'google_organic'
                WHEN %1$s.utm_source IS NULL AND (%1$s.referrer IS NULL OR %1$s.referrer = '') THEN 'direct'
                ELSE NULL
            END""";

    /** True iff a marketing.visits row joined on visitorColumn (e.g. "e.session_id") classifies
     * into one of the given sources. sources must already be validated against {@link #ALL} by
     * the caller (see each controller's parseSources) — never raw user input — since these values
     * are spliced directly into the SQL string. */
    static String visitInSources(String visitorColumn, Set<String> sources) {
        return """
                EXISTS (
                    SELECT 1 FROM marketing.visits vi
                    WHERE vi.visitor_id = %s AND (%s) IN (%s)
                )""".formatted(visitorColumn, VISIT_CASE.formatted("vi"), inList(sources));
    }

    /** True iff a marketing.contacts row (aliased contactAlias, e.g. "c2") classifies into one of
     * the given sources. Same validated-input requirement as {@link #visitInSources}. */
    static String contactInSources(String contactAlias, Set<String> sources) {
        return "(%s) IN (%s)".formatted(CONTACT_CASE.formatted(contactAlias), inList(sources));
    }

    /** Exposed for MarketingContactsRepository's PLATFORM_CASE-style single-value classification
     * (as opposed to the boolean "is it in this set" checks above). %1$s is the contacts alias. */
    static String contactChannelCase(String contactAlias) {
        return CONTACT_CASE.formatted(contactAlias);
    }

    private static String inList(Set<String> sources) {
        return sources.stream().map(s -> "'" + s + "'").collect(Collectors.joining(","));
    }
}
